#install.packages("httr2")
#install.packages("dplyr")
library(dplyr)
library(httr2)
######################
### Getting 1 page of data from OpenAlex
######################

# Build API request to OpenAlex
req <- request("https://api.openalex.org/works") %>%
  req_url_query(page = "1",
                `per-page` = "200",
                filter = "default.search:PLS-SEM",
                select = "abstract_inverted_index, doi, title",
                mailto="INSERT_OWN_EMAIL")
# Send the request and receive the results
results <- req %>%
  req_perform() %>%
  resp_body_json()
# Total number of responses
n_resp <- length(results$results)
# Insert into a dataframe
df <- data.frame(abstract = rep("", times = n_resp),
                 doi = rep("", times = n_resp),
                 title = rep("", times = n_resp)) %>%
  as_tibble()
# Handle if a field does not exist
nulls_as_text <- function(x){
  if(is.null(x)){""}else{x}
}
# Transform from list to dataframe format
for (i in 1:length(results$results)) {
  df[i,"abstract"] <- nulls_as_text(paste(names(results$results[[i]]$abstract_inverted_index), collapse = " "))
  df[i,"doi"] <- nulls_as_text(results$results[[i]]$doi)
  df[i,"title"] <- nulls_as_text(results$results[[i]]$title)
}
# View dataframe
df

######################
### Labeling 1 article with openai
######################
library(reticulate)
source_python("label_article_openai.py")
label_article_openai(topic = "Paper with new original methodological developments within PLS-SEM. The paper should not be review of old methods, but the original paper proposing the method", 
                     title = "PLS-SEM: Indeed a Silver Bullet", 
                     abstract = "Abstract Structural equation modeling (SEM) has become a quasi-standard in marketing and management research
                                 when it comes to analyzing the cause-effect relations between latent constructs. For most researchers, SEM 
                                 is equivalent carrying out covariance-based (CB-SEM). While researchers have basic understanding of CB-SEM, 
                                 them are only barely familiar with other useful approach SEM-partial least squares (PLS-SEM). The current paper 
                                 reviews PLS-SEM its algorithm, provides an overview can be appropriately applied, indicating potential limitations 
                                 for future research. authors conclude that path modeling, if indeed \"silver bullet\" estimating causal models 
                                 many theoretical empirical data situations. This article part following collections: Celebrating Impactful 
                                 Articles from Journal Marketing Theory Practice", 
                     api_key = "INSERT_OWN_OPENAI_API_KEY")



######################
### Labeling 1 article with openai, three variables as output
######################
library(reticulate)
source_python("label_article_openai2.py")
label_article_openai2(topic = "Paper with new original methodological developments within PLS-SEM. The paper should not be review of old methods, but the original paper proposing the method", 
                     title = "A Note on How to Conduct a Factor-Based PLS-SEM Analysis", 
                     abstract = "The composite-factor estimation dichotomy has been the epicenter of a long and ongoing debate among proponents detractors use partial least squares (PLS) 
                     approach for structural equation modeling (SEM). In this brief research note author discusses implementation new method to conduct factor-based PLS-SEM analyses, 
                     which could be solid step in resolution debate. This generates estimates both true composites factors, two stages, fully accounting measurement error. author's 
                     discussion is based on an illustrative model field e-collaboration. A Monte Carlo experiment suggests that parameters generated by are asymptotically unbiased. 
                     implemented as part software WarpPLS, starting version 5.0. provides enough details method's other venues such R GNU Octave.", 
                     api_key = "INSERT_OWN_OPENAI_API_KEY")

